export default [
  {
    name: 'Chlorpromazine',
    pronunciation: 'klor-PRO-ma-zeen',
    use: 'An antipsychotic medicine helps to adjust the levels of dopamine and other chemicals available in your brain to help with the symptoms.',
    'side-effects': [
      'Difficulty in swallowing, or any other symptoms like swelling in the mouth, tongue, face and throat, itching, rash, that could be an allergic reaction to the medicine',
      'Muscles going stiff or rigid with high fever, sweating, looking pale, feeling strange and fainting or losing consciousness, or very rapid or irregular heartbeat',
      'Skin reactions - rashes, flaking of the skin or red blisters on the skin',
    ],
  },
  {
    name: 'Diazepam',
    pronunciation: 'Die-A-zi-pam',
    use: 'Diazepam improves the effect of a chemical in the brain called gamma-aminobutyric acid (GABA). GABA is a chemical that blocks transmission across nerves in the brain and has a ‘calming effect’',
    'side-effects': [
      'extreme sleepiness that interferes with your daily life',
      'slurred speech',
      'headache',
      'light-headedness, a ‘spinning’ sensation, unsteadiness or clumsiness and loss of co-ordination (you may notice these even after a single dose and this may continue into the following day)',
      'confusion',
      'or memory loss (which may be experienced several hours after taking diazepam)',
      'seeing or sensing things that are not there',
      'unusual behaviour',
      'difficulty concentrating',
      'agitation/irritability',
      'getting overexcited or restless',
      'feeling very angry (rage), numbed emotions, or depression with thoughts of hurting or killing yourself',
    ],
  },
  {
    name: 'Methylphenidate (Ritalin)',
    pronunciation: 'MEE-thile-FEN-i-date',
    use: 'Methylphenidate is a Central Nervous Stimulant. You can take methylphenidate as tablets or capsules.',
    'side-effects': [
      'headache – try paracetamol or talk to your pharmacist about options to help',
      'feeling nervous',
      'not being able to sleep',
    ],
  },
  {
    name: 'Atomoxetine (Strattera)',
    pronunciation: 'A-tom-OX-et-een',
    use: 'Atomoxetine is not a central nervous stimulant, which makes it different from other treatments for Attention Deficit Hyperactivity Disorder ADHD.',
    'side-effects': [
      'feeling or having a very fast heartbeat, or an uneven heartbeat',
      'thinking about or feeling like killing yourself',
      'feeling aggressive, unfriendly or very angry',
      'having mood swings or mood changes',
      'having a serious allergic reaction with symptoms of swelling of the face and throat',
      'difficulty breathing',
      'hives (small raised, itchy patches of skin)',
      'fits (seizures)',
      'psychotic symptoms including hallucinations (hearing voices or seeing things which are not there), or believing things that are not true, or being suspicious',
    ],
  },
  {
    name: 'Lithium',
    pronunciation: 'LITH-ee-um',
    use: 'Lithium can be used to help a range of mental health conditions. Lithium helps to keep your mood from becoming too low or too high, which is why it is classed as a mood stabiliser medicine',
    'side-effects': [
      'Feeling unusually sleepy',
      'Severe hand shake (‘tremor’)',
      'Stomach ache along with feeling sick and having diarrhoea',
      'Muscle weakness',
      'Being unsteady on your feet',
      'Muscle twitches',
      'Slurring of words – so that it is difficult for others to understand what you are saying',
      'Blurred vision',
      'Confusion',
    ],
  },
  {
    name: 'Amitriptyline',
    pronunciation: 'Ammy-TRIP-ti-leen',
    use: 'Amitriptyline is a tricyclic antidepressant medicine. A tricyclic antidepressant medicine helps to lift your mood. They are used for other symptoms, however, including bedwetting and to help with nerve pain.',
    'side-effects': [
      'feeling sleepy',
      'dry mouth',
      'blurred eyesight, changes to your eyesight, or increased pressure in the eye',
      'constipation',
      'fever',
      'difficulty in going to pee',
    ],
  },
  {
    name: 'Fluoxetine',
    pronunciation: 'Flu-OX-et-een',
    use: 'Fluoxetine is a type of antidepressant called a Selective Serotonin Re-uptake Inhibitor. It can be used to help with low mood and anxiety.',
    'side-effects': [
      'Difficulty sleeping (insomnia)',
      'headache and feeling tired',
      'loose poo (diarrhoea)',
      'feeling sick (nausea)',
    ],
  },
  {
    name: 'Sertraline',
    pronunciation: 'SIR-tra-leen',
    use: 'A Selective Serotonin Re-uptake Inhibitor (SSRI) helps make more serotonin available in your brain.',
    'side-effects': [
      'thoughts of harming yourself or taking your own life.',
      'high fever, agitation, confusion, trembling, sweating',
      'diarrhoea (loose poo)',
      'fast heartbeat or weird movements of your muscles',
      'if you feel restless and are not able to sit or stand still after you start to take sertraline',
      'if you feel overexcited or very happy, as this may be a manic episode',
      'repeated movements of your face and tongue that you cannot control',
    ],
  },
  {
    name: 'Citalopram',
    pronunciation: 'sit-AL-o-pram',
    use: 'Citalopram is a Selective Serotonin Re-uptake Inhibitor. It helps make more serotonin available in your brain.',
    'side-effects': [
      'Difficulty sleeping (insomnia)',
      'Dry mouth',
      'Feeling sick (nausea) or vomiting',
    ],
  },
];
